export function createReceipt({
  submitted,
  modeResolved,
  projectResolved,
  url,
  runId = null,
  artifactDir = null,
  surface = null,
  proofLevel = null,
  targetWindowHandle = null,
  conversationUrl = null,
  screenshotPath = null,
  submitAttempted = false,
  submitAttemptMethod = null,
  failureClass = null,
  failureReason = null,
  attemptCount = 1,
  finalAction = null,
  debugArtifacts = null,
  notes = []
}) {
  return {
    submitted,
    timestamp: new Date().toISOString(),
    modeResolved,
    projectResolved,
    url,
    runId,
    artifactDir,
    surface,
    proofLevel,
    targetWindowHandle,
    conversationUrl,
    screenshotPath,
    submitAttempted,
    submitAttemptMethod,
    failureClass,
    failureReason,
    attemptCount,
    finalAction,
    debugArtifacts,
    notes
  };
}

export function createFailureReceipt({
  error,
  screenshotPath = null,
  url = null,
  runId = null,
  artifactDir = null,
  surface = null,
  proofLevel = null,
  targetWindowHandle = null,
  conversationUrl = null,
  submitAttempted = false,
  submitAttemptMethod = null,
  failureClass = null,
  failureReason = null,
  attemptCount = 1,
  finalAction = null,
  debugArtifacts = null,
  notes = []
}) {
  return {
    submitted: false,
    timestamp: new Date().toISOString(),
    error: {
      code: error.code || 'UNEXPECTED_ERROR',
      step: error.step || 'unknown',
      message: error.message
    },
    url,
    runId,
    artifactDir,
    surface,
    proofLevel,
    targetWindowHandle,
    conversationUrl,
    screenshotPath,
    submitAttempted,
    submitAttemptMethod,
    failureClass,
    failureReason,
    attemptCount,
    finalAction,
    debugArtifacts,
    notes
  };
}
